log:
  name: new-shop-admin-srv # logger的名称
  development: true # 是否开启开发模式，开发模式下会打印调试信息，默认 false
  level: debug # 日志级别，优先级从低到高依次为: debug, info, warn, error, dpanic, panic, fatal
  format: console # 支持的日志输出格式，目前支持console和json两种。console实际上是基于console的编码器，json是json编码器
  enable-color: true # 是否开启颜色输出，true:是，false:否
  disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件行号
  disable-stacktrace: false # 是否在panic及以上级别禁止打印堆栈信息
  output-paths: logs/new-shop-admin-srv.log,stdout # 支持输出到多个输出，逗号分开。支持文件、标准输出
  error-output-paths: logs/new-shop-admin-srv.error.log # zap内部(非业务)错误日志输出路径

registry:
  address: 192.168.145.128:8500
  scheme: http

